spring:
  application:
    name: demo
  output:
    ansi:
      enabled: always
client:
  baseUrl: http://localhost:8089
logging:
  level:
    root: INFO
    com.example.toshio: DEBUG
    org.springframework.web: DEBUG
    org.springframework.boot: DEBUG
    org.springframework: DEBUG
